[%
    T = {
        tool_1                                     = "Koha-Suomi - Print notices",
        tool_3                                     = "Main page",
        tool_4                                     = "Plugins",
        tool_5                                     = "Print notices",
        tool_6                                     = "Hold reminders",
        tool_7                                     = "1. overdue notice",
        tool_8                                     = "2. overdue notice",
        tool_9                                     = "An error occurred:",
        tool_10                                    = "Return",
        tool_11                                    = "Print",
        tool_12                                    = "Timestamp",
        tool_13                                    = "Patron ID",
        tool_14                                    = "Library",
        tool_15                                    = "Email",
        tool_16                                    = "Library email",
        tool_17                                    = "Actions",
        tool_18                                    = "Cancel",
        tool_19                                    = "No pending notices!",
    }
%]
