[%
    T = {
        tool_1                                     = "Koha-Suomi - Tulosta ilmoituksia",
        tool_3                                     = "Etusivu",
        tool_4                                     = "Liitännäiset",
        tool_5                                     = "Tulosta ilmoituksia",
        tool_6                                     = "Noutoilmoitukset",
        tool_7                                     = "1. muistutus",
        tool_8                                     = "2. muistutus",
        tool_9                                     = "Tapahtui virhe:",
        tool_10                                    = "Takaisin",
        tool_11                                    = "Tulosta",
        tool_12                                    = "Aikaleima",
        tool_13                                    = "Asiakas ID",
        tool_14                                    = "Kirjastopiste",
        tool_15                                    = "Sähköposti",
        tool_16                                    = "Kirjaston sähköposti",
        tool_17                                    = "Toiminnot",
        tool_18                                    = "Peruuta",
        tool_19                                    = "Ei odottavia ilmoituksia!",
    }
%]
