[%
    T = {
        tool_1                                     = "Koha-Suomi - Skriv ut meddelanden",
        tool_3                                     = "Huvudsida",
        tool_4                                     = "Plugins",
        tool_5                                     = "Skriv ut meddelanden",
        tool_6                                     = "Reservationsmeddelanden",
        tool_7                                     = "1. förseningsmeddelande",
        tool_8                                     = "2. förseningsmeddelande",
        tool_9                                     = "Ett fel uppstod:",
        tool_10                                    = "Tillbaka",
        tool_11                                    = "Utskrift",
        tool_12                                    = "Tidsstämpel",
        tool_13                                    = "Låntagare ID",
        tool_14                                    = "Bibliotek",
        tool_15                                    = "E-post",
        tool_16                                    = "Bibliotek e-post",
        tool_17                                    = "Funktions",
        tool_18                                    = "Avbryt",
        tool_19                                    = "Inga väntande meddelanden!",
    }
%]
